
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 02 21:10:16 CET 2019
//----------------------------------------------------

package yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int RETOURNE = 19;
  public static final int IDF = 20;
  public static final int EGAL = 8;
  public static final int OU = 24;
  public static final int CSTENTIERE = 21;
  public static final int LIRE = 7;
  public static final int INFERIEUR = 27;
  public static final int PARFERMER = 9;
  public static final int ECRIRE = 6;
  public static final int DIVISION = 32;
  public static final int FONCTION = 18;
  public static final int TANTQUE = 11;
  public static final int ALORS = 15;
  public static final int SUPERIEUR = 28;
  public static final int DIFFERENT = 26;
  public static final int REPETER = 13;
  public static final int NON = 29;
  public static final int MOINS = 31;
  public static final int POINTVIRGULE = 5;
  public static final int FINTANTQUE = 12;
  public static final int EGALLOGIQUE = 23;
  public static final int SINON = 16;
  public static final int TYPE = 22;
  public static final int EOF = 0;
  public static final int MULTIPLICATION = 33;
  public static final int ET = 25;
  public static final int SI = 14;
  public static final int error = 1;
  public static final int PAROUVERT = 10;
  public static final int DEBUT = 3;
  public static final int ADDITION = 30;
  public static final int FINSI = 17;
  public static final int FIN = 4;
  public static final int PROGRAMME = 2;
}

