
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Feb 02 11:20:48 CET 2019
//----------------------------------------------------

package yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int ECRIRE = 6;
  public static final int IDF = 11;
  public static final int DEBUT = 3;
  public static final int PROGRAMME = 2;
  public static final int POINTVIRGULE = 5;
  public static final int FIN = 4;
  public static final int EOF = 0;
  public static final int EGAL = 8;
  public static final int LIRE = 7;
  public static final int TYPE = 13;
  public static final int PAROUVERT = 10;
  public static final int PARFERMER = 9;
  public static final int error = 1;
  public static final int CSTENTIERE = 12;
}

