
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Feb 02 15:46:12 CET 2019
//----------------------------------------------------

package yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int IDF = 11;
  public static final int EGAL = 8;
  public static final int OU = 15;
  public static final int CSTENTIERE = 12;
  public static final int LIRE = 7;
  public static final int INFERIEUR = 18;
  public static final int PARFERMER = 9;
  public static final int ECRIRE = 6;
  public static final int DIVISION = 23;
  public static final int SUPERIEUR = 19;
  public static final int DIFFERENT = 17;
  public static final int NON = 20;
  public static final int MOINS = 22;
  public static final int POINTVIRGULE = 5;
  public static final int EGALLOGIQUE = 14;
  public static final int TYPE = 13;
  public static final int EOF = 0;
  public static final int MULTIPLICATION = 24;
  public static final int ET = 16;
  public static final int error = 1;
  public static final int PAROUVERT = 10;
  public static final int DEBUT = 3;
  public static final int ADDITION = 21;
  public static final int FIN = 4;
  public static final int PROGRAMME = 2;
}

