
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jan 14 12:12:33 CET 2019
//----------------------------------------------------

package yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodeLexicaux {
  /* terminals */
  public static final int ECRIRE = 6;
  public static final int IDF = 7;
  public static final int DEBUT = 3;
  public static final int PROGRAMME = 2;
  public static final int POINTVIRGULE = 5;
  public static final int FIN = 4;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int CSTENTIERE = 8;
}

