
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int ECRIRE = 6;
  public static final int IDF = 7;
  public static final int DEBUT = 3;
  public static final int PROGRAMME = 2;
  public static final int POINTVIRGULE = 5;
  public static final int FIN = 4;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int CSTENTIERE = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAMME",
  "DEBUT",
  "FIN",
  "POINTVIRGULE",
  "ECRIRE",
  "IDF",
  "CSTENTIERE"
  };
}

